[project]
name = "cotton2k"
version = "5.0.0a8"

[project.optional-dependencies]
docs = ["sphinx", "sphinxcontrib-bibtex"]

[build-system]
requires = ["pyproject-toml == 0.10.0"]
build-backend = "pyproject_toml.build_system.build_backend"
